use_frameworks!

platform :ios, '12.0'

target 'RxSwiftDitto_Example' do
  pod 'RxSwiftDitto', path: '../'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'RxDataSources', '~> 5.0.0'
  pod 'Fakery', '=5.1.0'
  pod 'DittoSwift', '1.1.5'

  target 'RxSwiftDitto_Tests' do
    inherit! :search_paths
    pod 'Fakery', '=5.1.0'

  end
end
